name: wifi_example
description: Demonstrates how to use the wifi plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.5.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - images/wifi1.png
    - images/wifi2.png
    - images/wifi3.png

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  wifi:
    path: ../
