name: wifi
description: Flutter plugin providing WiFi.
homepage: https://github.com/CodeAtlas/wifi
version: 0.2.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.5.0 <3.0.0"

flutter:
  plugin:
    androidPackage: it.codeatlas.flutter.wifi
    pluginClass: WifiPlugin

dependencies:
  flutter:
    sdk: flutter
