name: wifi
description: Flutter plugin providing WiFi.
homepage: https://github.com/CodeAtlas/wifi
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: it.codeatlas.flutter.wifi
    pluginClass: WifiPlugin

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"
